My branch
JamilaHajAhmad/ruby-code pull request #1
Opened 2024-10-10 16:52 UTC by JamilaHajAhmad

2024-10-12 10:23 UTC, MaiAbuthraa requested changes

2024-10-12 10:23 UTC, MaiAbuthraa commented on csv_viewer/first-task.rb
> +    puts "No CSV files found in the directory."
fix the indentation

```suggestion
  puts "No CSV files found in the directory."
```

2024-10-12 10:23 UTC, MaiAbuthraa commented on csv_viewer/first-task.rb
> +
Good work, but move all these classes to separated files

2024-10-12 10:23 UTC, MaiAbuthraa commented on csv_viewer/first-task.rb
> +selector = Selector.new(fetcher.files)
It's not good to have free code like that. Everything has to be inside a class.

2024-10-12 10:23 UTC, MaiAbuthraa commented on csv_viewer/first-task.rb
> +
where are the Gemfile and Gemfile.lock?

2024-10-18 09:00 UTC, JamilaHajAhmad commented
Hello Ms. Mai,
All of the requested changes has been addressed in my last commit,
Please check it out,
Thank you

2024-10-31 08:13 UTC, merged